name: Release builder
run-name: Build ${{ github.ref_name }}

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt update && sudo apt install lsb-release pkg-config wget software-properties-common gnupg git tar xz-utils curl cmake make autoconf libtool -y

    - name: Install Clang
      run: | 
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        export AR=/usr/bin/llvm-ar-16
        export AS=/usr/bin/llvm-as-16
        export CC=/usr/bin/clang-16
        export CXX=/usr/bin/clang++-16
        export LD=/usr/bin/llvm-ld-16
        export RANLIB=/usr/bin/llvm-ranlib-16
        export STRIP=/usr/bin/llvm-strip-16
    
    - name: Get iperf3 source
      run: git clone --depth 1 --branch 3.14 https://github.com/esnet/iperf.git

    - name: Get iperf3 source
      run: cd iperf && ./configure -h

    - name: Get iperf3 source
      run: cd iperf && ls -la
