name: Builder
run-name: Build ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt update && sudo apt install lsb-release pkg-config wget software-properties-common gnupg git tar xz-utils curl cmake make autoconf libtool -y

    - name: Install Clang
      run: | 
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
    
    - name: Get iperf3 source
      run: git clone --depth 1 --branch 3.14 https://github.com/esnet/iperf.git


    - name: configure iperf3
      run: |
        cd iperf 
        export AR=/usr/bin/llvm-ar-16
        export AS=/usr/bin/llvm-as-16
        export CC=/usr/bin/clang-16
        export CXX=/usr/bin/clang++-16
        export LD=/usr/bin/llvm-ld-16
        export RANLIB=/usr/bin/llvm-ranlib-16
        export STRIP=/usr/bin/llvm-strip-16
        ./configure --enable-static-bin

    - name: make iperf3
      run: cd iperf && make

    - name: install iperf3
      run: cd iperf && sudo make install

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        tag_name: ${{ github.ref }}
        files: /usr/local/bin/iperf3 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}